Support a NULL EventSink in Stalker
frida/frida-gum pull request #487
Opened 2020-08-24 13:14 UTC by meme

This PR is still in the proposal phase as I haven't added ARM64 or MIPS support nor reasonable tests.

For background: in my personal project hotwax, my [`event_sink.c`](https://github.com/meme/hotwax/blob/master/src/event_sink.c) simply acts as a stub which does nothing (and returns a query_mask of 0). Now, in another project where I use the Frida Stalker, I've run into the same problem: I do not need an EventSink, but are required to provide one.

So, I propose that we allow EventSink to be `NULL` so that a user can provide ONLY a transformer and nothing else. Or alternatively, they can provide no Transformer or EventSink (not sure what the use-case is for this, but it is now allowed)

So my goals for this PR are _speed_. I want to provide reasonable speed benefits if you do not provide an EventSink. This is why I ask for your feedback @oleavr to see:
1) If this is reasonable
2) How we can design this so that it provides the most speed benefit

2020-08-24 13:39 UTC, meme commented
I agree that if-checks everywhere is not great, I was getting nervous that I may have missed some... I will re-work this PR with NullSink as I agree that is more suitable.

2020-08-25 12:41 UTC, meme commented
Integrated a `DefaultEventSink` and I agree it makes much more sense. The question is now: how should we be testing this considering there is a bit of overlap with other Stalker tests?

2020-08-25 17:56 UTC, oleavr requested changes
Yay, thanks! 🤘

2020-08-25 17:56 UTC, oleavr commented on gum/gumeventsink.h
> +                      DEFAULT_EVENT_SINK, GObject)
```suggestion
    DEFAULT_EVENT_SINK, GObject)
```

Hanging indents should be 4 spaces. (Just realised we're already a bit inconsistent when using these macros, ugh.)

2020-08-25 17:56 UTC, oleavr commented on gum/gumeventsink.h
> +GUM_API GumEventSink* gum_event_sink_make_default (void);
```suggestion
GUM_API GumEventSink * gum_event_sink_make_default (void);
```

2020-08-25 17:56 UTC, oleavr commented on tests/core/arch-x86/stalker-x86.c
> +  TESTENTRY (follow_me_nullable_event_sink)
```suggestion
  TESTENTRY (follow_me_should_support_nullable_event_sink)
```

2020-08-25 17:56 UTC, oleavr commented on gum/gumeventsink.c
> +static void gum_default_event_sink_class_init (GumDefaultEventSinkClass* klass)
```suggestion
static void
gum_default_event_sink_class_init (GumDefaultEventSinkClass * klass)
```

(Here and elsewhere.)

2020-08-25 18:19 UTC, meme commented
Presumably these tests should be ported to the respective architectures, I can make them but I do not have the hardware to test all platforms currently. Is this something you'll do post-review, or is there a CI I can test it on?

2020-08-26 14:28 UTC, oleavr commented
> Presumably these tests should be ported to the respective architectures, I can make them but I do not have the hardware to test all platforms currently. Is this something you'll do post-review, or is there a CI I can test it on?

That would be great! Our CI doesn't yet run tests on those platforms, but it should be fairly safe to transplant the exact same code due to how similar the implementations are.

2020-08-26 14:33 UTC, oleavr requested changes

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +                                               gpointer iface_data);
Hanging indents should be 4 spaces.

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +                                            const GumEvent * ev);
Hanging indents should be 4 spaces.

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +gum_default_event_sink_iface_init (gpointer g_iface, gpointer iface_data)
Style violation, should only be one argument per line.

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +  object_class->finalize = gum_default_event_sink_finalize;
```suggestion

  object_class->finalize = gum_default_event_sink_finalize;
```

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +  iface->query_mask = gum_default_event_sink_query_mask;
```suggestion

  iface->query_mask = gum_default_event_sink_query_mask;
```

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +}
If a `dispose` or `finalize` implementation does nothing but chain up, it should be omitted.

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +gum_default_event_sink_query_mask(GumEventSink * sink)
```suggestion
gum_default_event_sink_query_mask (GumEventSink * sink)
```

2020-08-26 14:33 UTC, oleavr commented on gum/gumeventsink.c
> +gum_default_event_sink_process (GumEventSink * sink, const GumEvent * ev)
One argument per line (see earlier comment).

2020-08-31 08:20 UTC, oleavr requested changes

2020-08-31 08:20 UTC, oleavr commented on gum/gumeventsink.c
> +gum_event_sink_make_default (void)
Let's move this right before `gum_default_event_sink_class_init()` as this is higher level so it belongs higher up.

2020-08-31 08:20 UTC, oleavr commented on tests/core/arch-arm/stalker-arm.c
> +TESTCASE (follow_me_should_support_nullable_event_sink) {
```suggestion
TESTCASE (follow_me_should_support_nullable_event_sink)
{
```

(Here and the in the corresponding code for the other archs.)

2020-09-01 16:59 UTC, oleavr approved these changes
Yay! 🙌

2020-09-01 16:59 UTC, merged