Added fast interceptor implementation for x86/64
frida/frida-gum pull request #685
Opened 2022-10-27 16:39 UTC by WorksButNotTested

2022-11-22 19:42 UTC, oleavr requested changes
Thanks! 💥  (Sorry for the delay here, been some intense weeks!)

2022-11-22 19:42 UTC, oleavr commented on gum/backend-x86/guminterceptor-x86.c
> +  if (ctx->trampoline_slice != NULL && ctx->type != GUM_INTERCEPTOR_TYPE_FAST)
This will leak memory if successful in fast mode.

2022-11-22 19:42 UTC, oleavr commented on gum/backend-x86/guminterceptor-x86.c
> +  }
```suggestion
    gum_x86_writer_put_jmp_address (cw, GUM_ADDRESS (ctx->replacement_function));
  else
    gum_x86_writer_put_jmp_address (cw, GUM_ADDRESS (ctx->on_enter_trampoline));
```

Another issue is that the first statement exceeds 80 cols and needs further tweaks. (Too risky/tedious to suggest this change from the GitHub UI.)

2022-11-22 19:42 UTC, oleavr commented on gum/guminterceptor-priv.h
> +} ;
```suggestion
};
```

2022-11-22 19:42 UTC, oleavr commented on gum/guminterceptor.c
> +gum_interceptor_replace_ex (GumInterceptor * self,
```suggestion
gum_interceptor_replace_full (GumInterceptor * self,
```

Err, or something like that... at least GLib uses `_full` in a few places. Another option is `gum_interceptor_replace_with_type`. What do you think?

2022-11-22 19:42 UTC, oleavr commented on gum/guminterceptor.c
> +                            guint type,
Should use the enum here.

2022-11-22 19:42 UTC, oleavr commented on gum/guminterceptor.c
>    ctx = gum_function_context_new (self, function_address);
Should add it as a "constructor" argument instead of setting it afterwards.

2022-11-22 19:42 UTC, oleavr commented on tests/core/interceptor.c
> +    for (gsize i = 0; i < 1000; i++)
```suggestion
  for (gsize i = 0; i != 1000; i++)
```

2022-11-23 09:13 UTC, WorksButNotTested commented
It's no worries. Appreciate you were busy with the new release. Hopefully I've got the changes sorted.

2022-12-01 22:28 UTC, oleavr requested changes
Thanks! I'll take care of the final tweaks.

2022-12-01 22:28 UTC, oleavr commented on gum/backend-arm/guminterceptor-arm.c
>          dedicated);
```suggestion
        self->allocator, &caller, return_address, deflector_target, dedicated);
```

2022-12-01 22:28 UTC, oleavr commented on gum/backend-arm64/guminterceptor-arm64.c
> +  }
```suggestion
    on_enter = GUM_ADDRESS (ctx->replacement_function);
  else
    on_enter = GUM_ADDRESS (ctx->on_enter_trampoline);
```

2022-12-01 22:28 UTC, oleavr commented on gum/backend-arm64/guminterceptor-arm64.c
> +   if (ctx->type == GUM_INTERCEPTOR_TYPE_FAST)
```suggestion
  if (ctx->type == GUM_INTERCEPTOR_TYPE_FAST)
```

2022-12-01 22:28 UTC, oleavr commented on gum/backend-x86/guminterceptor-x86.c
> +      self->allocator, &spec, default_alignment);
```suggestion
        self->allocator, &spec, default_alignment);
```

2022-12-01 22:28 UTC, oleavr commented on gum/backend-x86/guminterceptor-x86.c
> +
```suggestion
```

2022-12-01 22:28 UTC, oleavr commented on gum/backend-x86/guminterceptor-x86.c
> +    gum_x86_writer_put_bytes (cw, (guint8 *) &ctx, sizeof (GumFunctionContext *));
```suggestion
    gum_x86_writer_put_bytes (cw, (guint8 *) &ctx,
        sizeof (GumFunctionContext *));
```

2022-12-01 22:28 UTC, oleavr commented on gum/backend-x86/guminterceptor-x86.c
> +    gum_x86_writer_put_jmp_address (cw, GUM_ADDRESS (ctx->on_enter_trampoline));
```suggestion
  if (ctx->type == GUM_INTERCEPTOR_TYPE_FAST)
  {
    gum_x86_writer_put_jmp_address (cw,
        GUM_ADDRESS (ctx->replacement_function));
  }
  else
  {
    gum_x86_writer_put_jmp_address (cw,
        GUM_ADDRESS (ctx->on_enter_trampoline));
  }
```

2022-12-01 22:28 UTC, oleavr commented on gum/guminterceptor.c
> +      function_address, &error);
```suggestion
  function_ctx =
      gum_interceptor_instrument (self, type, function_address, &error);
```

2022-12-01 22:28 UTC, oleavr commented on tests/core/interceptor.c
> +static gpointer (*target_function_fast) (GString * str) = NULL;
```suggestion
static gpointer (* target_function_fast) (GString * str) = NULL;
```

2022-12-01 22:28 UTC, oleavr commented on tests/core/interceptor.c
> +      GUM_REPLACE_OK);
```suggestion
      target_function, replacement_target_function, NULL, NULL),
      ==, GUM_REPLACE_OK);
```

2022-12-01 22:28 UTC, oleavr commented on tests/core/interceptor.c
> +      GUM_REPLACE_WRONG_TYPE);
```suggestion
      target_function, replacement_target_function, NULL),
      ==, GUM_REPLACE_WRONG_TYPE);
```

2022-12-02 00:39 UTC, merged

2022-12-02 06:44 UTC, WorksButNotTested commented
Awesome. Thanks for wrapping that up!