debug-symbol: Ensure path is absolute and add column field
frida/frida-gum pull request #692
Opened 2022-11-29 14:51 UTC by mrmacete

The `file_name` field is now an absolute path on Darwin too, the `column` field has also been added to all existing backends.

`file_name` is now also canonicalized in darwin and libdwarf backends.

2022-11-29 16:52 UTC, mrmacete commented
hmm this test fails consistently (tried to rerun it a few times too) https://github.com/frida/frida-gum/actions/runs/3575216331/jobs/6013659816

but if it's related to these changes then i don't know how

2022-12-02 00:45 UTC, oleavr requested changes
Thanks, great job! 🔥

2022-12-02 00:45 UTC, oleavr commented on gum/backend-darwin/gumdarwinsymbolicator.c
> +    gchar * canonicalized = NULL;
```suggestion
    gchar * canonicalized;
```

2022-12-02 00:45 UTC, oleavr commented on gum/backend-libdwarf/gumsymbolutil-libdwarf.c
> +  gchar * canonicalized = NULL;
```suggestion
  gchar * canonicalized;
```

2022-12-02 00:45 UTC, oleavr commented on gum/backend-libdwarf/gumsymbolutil-libdwarf.c
> +  g_free (canonicalized);
```suggestion
  g_free (canonicalized);
  g_free (source.path);
```

2022-12-02 00:45 UTC, oleavr commented on tests/core/backtracer.c
> +  g_assert_true (rad.column == 3);
```suggestion
  g_assert_cmpuint (rad.column, ==, 3);
```

2022-12-02 00:46 UTC, merged